version: 2.1
jobs:
    typecheck:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn install
            - run: yarn typecheck
    build:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn install
            - run: yarn build
    test:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn install
            - run: yarn test
    lint:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn install
            - run: yarn lint
workflows:
    automatic:
        jobs:
            - typecheck
            - build
            - test
            - lint
