contact_links:
    - name: 📃 Documentation Issue
      url: https://github.com/reactjs/reactjs.org/issues/new
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🤔 Questions and Help
      url: https://stackoverflow.com/questions/tagged/react
      about: This is    sue tracker is not for questions. Please ask questions here.